name: reconnect_yaml
main: net.md_5.bungee.module.reconnect.yaml.PluginYaml
version: git:reconnect_yaml:1.14-SNAPSHOT:a21445c:unknown
description: Provides reconnect location functionality in locations.yml
author: WaterfallMC
